### ISSUE TITLE
Pension_html Request Error in Chrome

### ISSUE THREAD

**Issue by zooomg** [Exitsoftware/Hyuga_Web_Version#5]
XMLHttpRequest cannot load file:///Users/ZOOOMG/Hyuga_Web_Version/js/parse_inn.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by yoonjeewoo** [comment]
Hey plz load file on your server chome blocked it
